shop123/Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shop123.Controllers
{
    public class SellerController : Controller
    {
        // GET: Seller
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Seller()
        {

            var seller = from p in (new Models.shop123Entities2()).orders select p;
            //var sku = from k in (new Models.shop123Entities()).sku select k;
            return View(seller);
        }

        public ActionResult sellerPage()
        {
            ViewModel.sellerPage sp = new ViewModel.sellerPage();
            Models.shop123Entities2 shop = new Models.shop123Entities2();
            var products = shop.spu.Join(shop.sku,
                x => x.id,
                y => y.spuId,
                (x, y) => new { x = sp.spu, y = sp.sku }
                );
            return View(products.ToList());
        }
    }


}

shop123/Views/Seller/Seller.cshtml
@model IEnumerable<shop123.Models.orders>
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>賣家中心</title>
    <link href="~/Content/seller.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="header-nav">
            <div class="nav-left">
                <a href="#"><img src="~/Images/logo.png" width="180" height="100" alt=""></a>
                <h2>賣家中心</h2>
            </div>
            <div class="nav-right">
                <span>xxx 您好，</span><a href="#">登出</a>
            </div>
        </div>
        <div class="main row">
            <div class="list col-lg-2 col-md-3 col-sm-4 col-12">
                <button class="order-manage">訂單管理</button>
                <button class="product-manage">商品管理</button>
            </div>
            <div class="content col-lg-10 col-md-9 col-sm-8 col-12" id="tabs">
                <div class="a-ul">
                    <ul class="show-list">
                        <li><a href="#" class="all">全部</a></li>
                        <li><a href="#" class="notpay">未付款</a></li>
                        <li><a href="#" class="back">已完成</a></li>
                        <li><a href="#" class="go">退款/退貨</a></li>
                    </ul>
                    <ul class="show-product">
                        <li><a href="#">所有商品存貨</a></li>
                        <li><a href="#">已售完商品</a></li>
                    </ul>
                    <table class="table allList">
                        <tr>
                            <td>訂單編號</td>
                            <td>會員編號</td>
                            <td>送貨編號</td>
                            <td>訂單狀態</td>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.memberId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.deliveryId)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.orderState)
                                </td>
                            </tr>
                        }
                    </table>

                    <table class="table no-pay">
                        <tr>
                            <td>訂單編號</td>
                            <td>會員編號</td>
                            <td>送貨編號</td>
                            <td>訂單狀態</td>
                            <td>測試</td>
                        </tr>

                        @foreach (var item in Model)
                        {
                            if (Convert.ToBoolean(item.orderState) == false)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.memberId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.deliveryId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.orderState)
                                    </td>
                                </tr>

                            }
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Scripts/seller.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</body>
</html>

shop123/Views/Seller/SellerAddItem.cshtml
@model shop123.Models.SpuModel

@{
    ViewBag.Title = "SellerAddItem";
}

<h2>SellerAddItem</h2>
<meta name="viewport" content="width=device-width" />
<title>drop</title>
@*@using (Html.BeginForm("SellerAddItem", "Seller", FormMethod.Post, new { @name = "dropzoneform", id = "dropzoneform", @enctype = "multipart/form-data" })) {*@
<link href="~/Scripts/dropzone/dropzone.min.css" rel="stylesheet" />
<script src="~/Scripts/dropzone/dropzone.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<style>
    .frame {
        background-color: #EDEDE9;
    }

    img {
        width: auto;
        height: auto;
        max-width: 100%;
        max-height: 100%;
    }

    textarea {
        resize: none;
        /* height: 500px; */
    }

    .uploadImag {
         display:none;
    }
</style>
<script>
    var count = 0;  //設定div裡面 spuImage的數字
    Dropzone.options.dropzoneform = {   //圖片拖曳設定參數
        addRemoveLinks: true,  //加入移除符號
        autoProcessQueue: false,  //關閉自動上傳功能
        maxFiles: 5,              
        maxFilesize: 5,   //單位為 MB
        dictDefaultMessage: '請點擊或將圖片拖曳至此區塊',
 
        init: function () {
            var zone = this;
            this.on('maxfilesexceeded', function (file) {  //圖片數量超過後，移除多餘圖片
                this.removeFile(file);

            });
            this.on('removedfile', function () {   
                count--;

            })
            this.on('addedfile', function () {
                count++;
            }),
                $('#save').on('click', function () {  //按下存檔後生成存放圖片欄位，設定是display:none
                    if (count != 0) {
                        let y = 0;
                        zone.processQueue();
                        for (let i = 0; i < count; i++) {
                            y++;
                            var img = zone.files[i].name;
                            $('.testzone').append('<input class="uploadImag" type="text" name="spuImg' + y + '"' + 'value="' + img + '"/>');
                        }
                    }
                    else {
                        alert('請至少上傳一張圖片');
                    }
                });
        }
    }

</script>
<div>
    <div id="mydrop">
        <form action="upload" class="dropzone" name="dropzoneform" id="dropzoneform" style="background-color: #EDEDE9"></form>
    </div>
    <button type="submit" id="btn">upload</button>
</div>

<form action="~/Seller/SellerAddItem" method="post">
    <div class="frame container testzone">

        <div class="container">
            <div class="d-flex flex-row align-items-center mb-4">

                <div class="form-outline flex-fill mb-0 mt-5">
                    <label class="form-label" for="spuName">商品名稱</label>
                    @*<input type="text" name="spuName" id="spuName" class="form-control" />*@
                    @Html.EditorFor(model => model.spuName, new { htmlAttributes = new { @class = "form-control", @name = "spuName", @id = "spuName" } })
                    @Html.ValidationMessageFor(model => model.spuName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="d-flex flex-row align-items-center mb-4">

                <div class="form-outline flex-fill mb-0">

                    <label class="form-label" for="catalogAId">商品分類</label>
                    <select class="form-control itemselect" name="catalogAId">
                        <option name="catalogAId" value="1">WOMAN</option>
                        <option name="catalogAId" value="2">MEN</option>
                        <option name="catalogAId" value="3">KIDS</option>
                        <option name="catalogAId" value="4">BABYS</option>
                    </select>

                </div>
            </div>

            <div class="d-flex flex-row align-items-center mb-4">
                <!-- <i class="fas fa-envelope fa-lg me-3 fa-fw"></i> -->
                <div class="form-outline flex-fill mb-0">

                    <label class="form-label" for="catalogBId">商品分類2</label>
                    <select class="form-control itemselect" name="catalogBId">
                        <option name="catalogBId" value="1">長袖</option>
                        <option name="catalogBId" value="2">短袖</option>
                        <option name="catalogBId" value="3">背心/小可愛</option>
                        <option name="catalogBId" value="4">襯衫</option>
                        <option name="catalogBId" value="5">洋裝</option>
                        <option name="catalogBId" value="6">外套</option>
                        <option name="catalogBId" value="7">長褲</option>
                        <option name="catalogBId" value="8">短褲</option>
                        <option name="catalogBId" value="9">裙子</option>
                        <option name="catalogBId" value="10">內褲</option>
                    </select>

                </div>
            </div>

            <div class="d-flex flex-row align-items-center mb-4">
                <!-- <i class="fas fa-envelope fa-lg me-3 fa-fw"></i> -->
                <div class="form-outline flex-fill mb-0">
                    <label class="form-label" for="spuPrice">商品價格</label>
                    <input type="text" name="spuPrice" id="price" class="form-control" />

                </div>
            </div>

            <div class="d-flex flex-row align-items-center mb-4">
                <!-- <i class="fas fa-envelope fa-lg me-3 fa-fw"></i> -->
                <div class="form-outline flex-fill mb-0">
                    <label class="form-label" for="spuInfo">商品敘述</label>
                    <textarea name="spuInfo" id="spuInfo" class="form-control"></textarea>

                </div>
            </div>


        </div>

        <div class="container">
            <div class="d-flex flex-row align-items-center mb-4">
                <!-- <i class="fas fa-envelope fa-lg me-3 fa-fw"></i> -->
                <div class="form-outline flex-fill mb-0">
                    <label class="form-label" for="spuShow">上架狀態</label>
                    <input type="text" name="spuShow" id="spuShow" class="form-control" placeholder="可填入上架 / 未上架 / 補貨中...等管理資訊" />

                </div>
            </div>
        </div>

        <div class="container d-flex justify-content-between">
            <input class="btn btn-secondary" type="button" value="回首頁">
            <input class="btn btn-secondary" type="submit" id="save" value="存檔">
            @*@Html.ActionLink("存檔", "upload", "Seller", new { @class = "btn btn-secondary", @id = "save" })*@
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

shop123/Views/Seller/sellerPage.cshtml
@model IEnumerable<shop123.ViewModel.sellerPage>
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>賣家首頁</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/sellerPage.css">
</head>
<body>
    <div class="container">
        <div class="nav-info">
            <div class="nav-left">
                <a href="#"><img src="images/logo.png" width="180" height="100" alt=""></a>
                <h2>賣家首頁</h2>
            </div>
            <div class="nav-right">
                <div class="nav-fight-sellerPage">
                    <span>前往→</span><a href="sellerPage.html">賣家中心</a>
                </div>
                <div class="nac-right-login">
                    <span>xxx 您好，</span><a href="#">登出</a>
                </div>
            </div>
        </div>
        <!--foreach資料-->
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</body>
</html>